[package]
name = "loancalc"
version = "0.1.0"
edition = "2021"

[dependencies]
dialoguer = "0.10.4"
prettytable-rs = "0.10.0"
rust_decimal = "1.31"
rust_decimal_macros = "1.31"
colored = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
